name: Monkeypatch sonatype github actions

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compare-tags:
    runs-on: ubuntu-latest
    outputs:
      tags-to-update: ${{ steps.filter-tags.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up git to compare tags
        run: |
          git remote add upstream https://github.com/sonatype/actions.git
          git fetch upstream --tags --force

      - name: Get tags from upstream
        id: get-upstream-tags
        run: |
          git tag --sort=-v:refname | jq -R -s -c 'split("\n") | map(select(length > 0))' > upstream_tags.json
      
      - name: Clean up local tags before fetching the ones from origin
        run: |
          git tag -d $(git tag -l)

      - name: Get tags from origin
        id: get-origin-tags
        run: |
          git fetch origin --tags
          git tag --sort=-v:refname | jq -R -s -c 'split("\n") | map(select(length > 0))' > origin_tags.json

      - name: Filter out-of-sync tags
        id: filter-tags
        run: |
          excluded_tags=""
          upstream_tags=$(cat upstream_tags.json | jq -r '.[]')
          origin_tags=$(cat origin_tags.json | jq -r '.[]')
          echo "Upstream tags: $upstream_tags"
          echo "Origin tags: $origin_tags"
          if [ -z "$excluded_tags" ]; then
            out_of_sync_tags=$(comm -3 <(echo "$upstream_tags" | tr ' ' '\n' | sort) <(echo "$origin_tags" | tr ' ' '\n' | sort | grep -v '^$'))
          else
            out_of_sync_tags=$(comm -3 <(echo "$upstream_tags" | tr ' ' '\n' | sort) <(echo "$origin_tags" | tr ' ' '\n' | sort | grep -v '^$') | grep -v -E "$(echo $excluded_tags | sed 's/ /|/g')" || true)
          fi
          echo "Out of sync tags: $out_of_sync_tags"
          if [ -z "$out_of_sync_tags" ]; then
            echo "No tags to update"
            echo "tags=[]" >> $GITHUB_OUTPUT
          else
            echo "Tags to update: $out_of_sync_tags"
            echo "tags=$(echo "$out_of_sync_tags" | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
          fi

  monkeypatch:
    needs: compare-tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.compare-tags.outputs.tags-to-update) }}
    if: ${{ needs.compare-tags.outputs.tags-to-update != '[]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Establish the committer identity
        run: |
          git config --global user.name "Patricio Perez"
          git config --global user.email "73832292+patricioperezv@users.noreply.github.com"

      - name: Add "sonatype/actions" as a Git remote and fetch it
        run: |
          git remote add upstream https://github.com/sonatype/actions.git
          git fetch upstream --tags --force
      
      - name: Checkout to a new branch pointing to the tag ${{ matrix.tag }}
        run: |
          git checkout -B ${{ matrix.tag }}-monkeypatch ${{ matrix.tag }}

      - name: Remove the workflow directory
        run: |
          rm -rf .github/workflows

      - name: Vandal the sonatype cli setup action to hardcode the DOWNLOAD_URL export
        run: |
          sed -i "s|download.sonatype.com|nexus.boaboa.org/repository/sonatype-downloads-raw-proxy|g" setup-iq-cli/dist/index.js

      - name: Prepend the README-prepend.md to the README.md
        run: |
          git show main:README-prepend.md > README-prepend.md
          cat README-prepend.md README.md > README.md.tmp
          mv README.md.tmp README.md
          rm README-prepend.md

      - name: Update action.yaml and action.yml files
        run: |
          find . -type f \( -name 'action.yaml' -o -name 'action.yml' \) -exec sed -i "s|sonatype/actions|${{ github.repository }}|g" {} +

      - name: Commit the changes
        run: |
          git add . && git commit -m "Boaboa monkeypatching the sonatype github actions"

      - name: Recreate the tag
        run: |
          git tag -f ${{ matrix.tag }}

      - name: Push the tag
        run: |
          git push origin refs/tags/${{ matrix.tag }} --force